import type { Metadata } from "next";
import { Host_Grotesk } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
const font = Host_Grotesk({
  subsets:['latin','latin-ext']
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased max-w-[1600px] mx-auto`}
      >
       <main>
        <Navbar/>
         {children}
       </main>
      </body>
    </html>
  );
}
